@extends('clients.layout') @section('title','Inicio') @section('content')
<x-page-header :title="$brand['system_name'] ?? 'Centro Financiero 360'" description="Panorama operativo construido con información real del sistema." eyebrow="Resumen adaptativo"><x-slot:actions><a href="{{route('applications.create')}}" class="btn-secondary"><i data-lucide="file-plus-2" class="icon"></i>Nueva solicitud</a><a href="{{route('clients.create')}}" class="btn-primary"><i data-lucide="user-plus" class="icon"></i>Nuevo cliente</a></x-slot:actions></x-page-header>
<section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
@foreach([
 ['Cartera activa','C$ '.number_format((float)$stats['activePortfolio'],2),$stats['activeLoans'].' créditos','landmark','indigo','loans.index'],
 ['Monto colocado','C$ '.number_format((float)$stats['placed'],2),$stats['clients'].' clientes','banknote','violet','loans.index'],
 ['Cobros del día','C$ '.number_format((float)$stats['collectedToday'],2),$stats['routesToday'].' rutas programadas','hand-coins','emerald','collections.index'],
 ['Índice de mora',$stats['delinquencyRate'].'%',$stats['delinquentLoans'].' créditos en mora','bell','rose','loans.index'],
] as [$label,$value,$note,$icon,$color,$route])<a href="{{route($route)}}" class="metric group"><div class="flex items-start justify-between"><span class="grid h-9 w-9 place-items-center rounded-lg bg-{{$color}}-50 text-{{$color}}-600"><i data-lucide="{{$icon}}" class="icon"></i></span><i data-lucide="arrow-up-right" class="icon text-slate-300 transition group-hover:text-indigo-500"></i></div><p class="mt-4 text-[11px] font-medium text-slate-500">{{$label}}</p><p class="mt-1 text-xl font-semibold tabular-nums">{{$value}}</p><p class="mt-2 text-[10px] text-slate-400">{{$note}}</p></a>@endforeach
</section>
<section class="mt-4 grid gap-4 xl:grid-cols-[1.35fr_.65fr]"><article class="card p-5"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold">Distribución de cartera</h2><p class="mt-1 text-[11px] text-slate-400">Proporción actual por comportamiento</p></div><span class="badge bg-indigo-50 text-indigo-700">{{$stats['activeLoans']}} activos</span></div>@php $healthy=max(0,100-$stats['delinquencyRate']); @endphp<div class="mt-8"><div class="flex h-4 overflow-hidden rounded-full bg-slate-100"><div class="bg-indigo-500 transition-all" style="width:{{$healthy}}%"></div><div class="bg-rose-500 transition-all" style="width:{{$stats['delinquencyRate']}}%"></div></div><div class="mt-4 flex flex-wrap gap-5 text-xs"><span><i class="mr-2 inline-block h-2 w-2 rounded-full bg-indigo-500"></i>Al día {{$healthy}}%</span><span><i class="mr-2 inline-block h-2 w-2 rounded-full bg-rose-500"></i>En mora {{$stats['delinquencyRate']}}%</span></div></div><div class="mt-8 grid gap-3 sm:grid-cols-3"><a href="{{route('applications.index',['status'=>'review'])}}" class="rounded-xl bg-violet-50 p-4"><p class="text-[10px] text-violet-600">Solicitudes pendientes</p><p class="mt-1 text-xl font-semibold text-violet-900">{{$stats['pendingApplications']}}</p></a><a href="{{route('routes.index')}}" class="rounded-xl bg-cyan-50 p-4"><p class="text-[10px] text-cyan-700">Rutas de hoy</p><p class="mt-1 text-xl font-semibold text-cyan-900">{{$stats['routesToday']}}</p></a><a href="{{route('clients.index')}}" class="rounded-xl bg-slate-50 p-4"><p class="text-[10px] text-slate-500">Clientes activos</p><p class="mt-1 text-xl font-semibold">{{$stats['clients']}}</p></a></div></article>
<article class="card overflow-hidden"><div class="section-heading"><h2 class="text-sm font-semibold">Actividad de cobranza</h2><p class="text-[11px] text-slate-400">Gestiones más recientes</p></div><div class="divide-y divide-slate-100">@forelse($recentCollections as $record)<div class="p-4"><div class="flex justify-between gap-3"><p class="text-xs font-semibold">{{$record->client->full_name}}</p><span class="text-[10px] text-slate-400">{{$record->recorded_at->diffForHumans()}}</span></div><p class="mt-1 text-[10px] text-slate-500">{{$record->collector->user->name}} · {{$record->outcome}}</p>@if($record->amount)<p class="mt-2 text-xs font-semibold text-emerald-700">C$ {{number_format((float)$record->amount,2)}}</p>@endif</div>@empty<x-empty-state title="Sin actividad reciente" icon="inbox" />@endforelse</div></article></section>
<section class="card mt-4 overflow-hidden"><div class="section-heading"><h2 class="text-sm font-semibold">Solicitudes recientes</h2><p class="text-[11px] text-slate-400">Procesos que requieren seguimiento</p></div><div class="divide-y divide-slate-100">@forelse($recentApplications as $application)<a href="{{route('applications.show',$application)}}" class="flex items-center gap-4 p-4 hover:bg-indigo-50/30"><span class="grid h-9 w-9 place-items-center rounded-lg bg-violet-50 text-violet-600"><i data-lucide="file-check-2" class="icon"></i></span><div class="min-w-0 flex-1"><p class="text-xs font-semibold">{{$application->number}} · {{$application->client->full_name}}</p><p class="mt-1 text-[10px] text-slate-400">{{$application->product->name}} · C$ {{number_format((float)$application->requested_amount,2)}}</p></div><x-status-badge :status="$application->status" /></a>@empty<x-empty-state title="Sin solicitudes" />@endforelse</div></section>
@endsection
