<script setup>
import { useForm } from '@inertiajs/vue3';
import { ref } from 'vue';
import AppLayout from '../../../Layouts/AppLayout.vue';
import PaginationLinks from '../../../components/ui/PaginationLinks.vue';
const props=defineProps({periods:Object,endpoints:Object});
const selected=ref(null); const action=ref(''); const form=useForm({notes:'',reason:''});
const endpoint=(template,id)=>template.replace('__PERIOD__',id);
const open=(period,next)=>{selected.value=period;action.value=next;form.reset();form.clearErrors();};
const submit=()=>{const url=endpoint(action.value==='close'?props.endpoints.close:props.endpoints.reopen,selected.value.id);form.post(url,{preserveScroll:true,onSuccess:()=>selected.value=null});};
</script>
<template><AppLayout title="Períodos contables" eyebrow="Control y trazabilidad" description="Bloquea meses cerrados y conserva evidencia de cualquier reapertura."><section class="card overflow-hidden"><div class="table-wrap"><table class="w-full"><thead><tr><th class="table-cell">Período</th><th class="table-cell">Movimientos</th><th class="table-cell">Borradores</th><th class="table-cell">Estado</th><th class="table-cell">Cierre</th><th class="table-cell"></th></tr></thead><tbody><tr v-for="period in periods.data" :key="period.id"><td class="table-cell"><strong>{{period.name}}</strong><small class="block text-slate-400">{{period.starts_on}} — {{period.ends_on}}</small></td><td class="table-cell">{{period.entries_count}}</td><td class="table-cell">{{period.draft_entries_count}}</td><td class="table-cell"><span class="badge" :class="period.status==='open'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-700'">{{period.status==='open'?'Abierto':'Cerrado'}}</span></td><td class="table-cell"><span v-if="period.closed_at">{{period.closed_at}}<small class="block text-slate-400">{{period.closed_by?.name}}</small></span><span v-else>—</span></td><td class="table-cell text-right"><button class="btn-soft" @click="open(period,period.status==='open'?'close':'reopen')">{{period.status==='open'?'Cerrar':'Reabrir'}}</button></td></tr></tbody></table></div><p v-if="!periods.data.length" class="empty-state">Los períodos se crean automáticamente con el primer asiento de cada mes.</p><PaginationLinks :links="periods.links"/></section><div v-if="selected" class="fixed inset-0 z-50 grid place-items-center bg-slate-950/55 p-4" @click.self="selected=null"><form class="card w-full max-w-lg p-6" @submit.prevent="submit"><h2 class="text-lg font-bold">{{action==='close'?'Cerrar':'Reabrir'}} {{selected.name}}</h2><p class="mt-2 text-sm text-slate-500">{{action==='close'?'Después del cierre no podrán registrarse ni contabilizarse movimientos en este período.':'La reapertura quedará registrada permanentemente en la bitácora.'}}</p><label class="field-label mt-5 block">{{action==='close'?'Notas de cierre':'Motivo de reapertura'}}<textarea v-if="action==='close'" v-model="form.notes" class="control" required></textarea><textarea v-else v-model="form.reason" class="control" required></textarea></label><p v-if="Object.keys(form.errors).length" class="mt-2 text-xs text-rose-600">{{Object.values(form.errors).join(' · ')}}</p><div class="mt-5 flex justify-end gap-2"><button type="button" class="btn-soft" @click="selected=null">Cancelar</button><button class="btn-primary" :disabled="form.processing">Confirmar</button></div></form></div></AppLayout></template>
