@extends('clients.layout')
@section('title',$route->exists?'Editar ruta':'Nueva ruta')
@section('content')
@php
    $editing=$route->exists;
    $selectedIds=old('client_ids',$editing?$route->stops->pluck('client_id')->all():[]);
    $lockedIds=$editing?$route->stops->filter(fn($stop)=>$stop->records->isNotEmpty())->pluck('client_id')->all():[];
    $input='control'; $label='field-label';
    $routeClientData = [
        'clients' => $clients->map(fn ($client) => $client->only(['id', 'code', 'full_name', 'address', 'municipality', 'neighborhood', 'latitude', 'longitude']))->values(),
        'selectedIds' => array_map('intval', $selectedIds),
        'lockedIds' => array_map('intval', $lockedIds),
        'cancelUrl' => route('routes.index'),
        'submitLabel' => $editing ? 'Guardar cambios' : 'Crear ruta',
    ];
@endphp
<div class="mb-4"><a href="{{route('routes.index',['date'=>$route->scheduled_date?->format('Y-m-d')])}}" class="flex items-center gap-2 text-xs font-semibold text-indigo-600"><i data-lucide="arrow-left" class="icon"></i>Rutas</a><h1 class="page-title mt-2">{{$editing?'Editar ruta de cobranza':'Nueva ruta de cobranza'}}</h1><p class="page-description">{{$editing?'Actualiza la planificación y los clientes asignados.':'Programa el recorrido y ordena las visitas del cobrador.'}}</p></div>
@if($errors->any())<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{$editing?route('routes.update',$route):route('routes.store')}}" class="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">@csrf @if($editing)@method('PUT')@endif
<section class="card h-fit p-6"><div class="mb-5 flex items-center gap-3"><span class="grid h-9 w-9 place-items-center rounded-xl bg-[#eeebff] text-indigo-600"><i data-lucide="route" class="icon"></i></span><div><h2 class="text-sm font-semibold">Planificación</h2><p class="text-[11px] text-slate-400">Responsable, fecha y salida</p></div></div><div class="space-y-5"><label class="{{$label}}">Nombre de la ruta *<input name="name" value="{{old('name',$route->name)}}" class="{{$input}}" required></label><div class="grid gap-4 sm:grid-cols-2"><label class="{{$label}}">{{$editing?'Fecha':'Fecha inicial'}} *<input id="scheduled-date" type="date" name="scheduled_date" value="{{old('scheduled_date',$route->scheduled_date?->format('Y-m-d')??today()->format('Y-m-d'))}}" class="{{$input}}" required></label>@unless($editing)<label class="{{$label}}">Fecha final<input id="scheduled-until" type="date" name="scheduled_until" value="{{old('scheduled_until')}}" min="{{old('scheduled_date',today()->format('Y-m-d'))}}" class="{{$input}}"><span class="mt-1 text-[10px] font-normal text-slate-400">Opcional. Se creará una ruta por cada día, incluyendo ambas fechas.</span></label>@endunless<label class="{{$label}}">Hora de salida<input type="time" name="starts_at" value="{{old('starts_at',$route->starts_at?substr($route->starts_at,0,5):'08:00')}}" class="{{$input}}"></label></div><label class="{{$label}}">Cobrador *<select name="collector_id" class="{{$input}}" required><option value="">Seleccionar</option>@foreach($sellers as $seller)<option value="{{$seller->id}}" @selected(old('collector_id',$route->collector_id)==$seller->id)>{{$seller->user->name}} · {{$seller->code}}</option>@endforeach</select></label><label class="{{$label}}">Notas<textarea name="notes" rows="3" class="{{$input}}">{{old('notes',$route->notes)}}</textarea></label></div></section>
<section class="card overflow-hidden"><div class="border-b border-slate-100 p-5"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold">Clientes de la ruta</h2><p class="mt-1 text-[11px] text-slate-400">Marca para agregar y desmarca para quitar. Los clientes con gestiones conservan su historial.</p></div><span id="selected-count" class="rounded-full bg-[#eeebff] px-3 py-1 text-[10px] font-semibold text-indigo-600">0 seleccionados</span></div><div class="mt-4 flex gap-2"><div class="relative flex-1"><i data-lucide="search" class="icon absolute left-3 top-3 text-slate-400"></i><input id="client-search" type="search" placeholder="Buscar por nombre, barrio o dirección" class="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 text-xs outline-none focus:border-indigo-300"></div><button id="select-mapped" type="button" class="rounded-xl bg-[#eeebff] px-3 text-[10px] font-semibold text-indigo-600">Seleccionar ubicados</button></div></div>
<div id="client-list" class="max-h-[500px] divide-y divide-slate-100 overflow-y-auto">@forelse($clients as $client)@php $locked=in_array($client->id,$lockedIds); @endphp<label data-client="{{strtolower($client->full_name.' '.$client->neighborhood.' '.$client->address)}}" data-mapped="{{$client->latitude&&$client->longitude?'1':'0'}}" class="client-row flex items-center gap-4 p-4 transition {{$locked?'cursor-not-allowed bg-slate-50':'cursor-pointer hover:bg-indigo-50/40'}}"><input type="checkbox" name="client_ids[]" value="{{$client->id}}" @checked(in_array($client->id,$selectedIds)) @disabled($locked) class="client-check rounded border-slate-300 text-indigo-500 focus:ring-indigo-400">@if($locked)<input type="hidden" name="client_ids[]" value="{{$client->id}}">@endif<span class="grid h-9 w-9 place-items-center rounded-xl bg-[#eeebff] text-indigo-600"><i data-lucide="map-pin" class="icon"></i></span><span class="min-w-0 flex-1"><span class="block text-sm font-semibold">{{$client->full_name}}</span><span class="block truncate text-[11px] text-slate-400">{{$client->neighborhood}}, {{$client->municipality}} · {{$client->address}}</span></span>@if($locked)<span class="text-[10px] font-semibold text-slate-500">Con gestión</span>@else<span class="text-[10px] font-semibold {{$client->latitude&&$client->longitude?'text-emerald-600':'text-amber-600'}}">{{$client->latitude&&$client->longitude?'En mapa':'Sin coordenadas'}}</span>@endif</label>@empty<div class="p-10 text-center text-sm text-slate-400">No hay clientes activos.</div>@endforelse</div>
<div class="flex items-center justify-between border-t border-slate-100 p-5"><p class="text-[10px] text-slate-400">Las visitas quedan en el orden mostrado.</p><div class="flex gap-2"><a href="{{route('routes.index')}}" class="rounded-lg border border-slate-200 px-5 py-2.5 text-xs font-semibold text-slate-500">Cancelar</a><button class="flex items-center gap-2 rounded-lg bg-indigo-500 px-5 py-2.5 text-xs font-semibold text-white"><i data-lucide="save" class="icon"></i>{{$editing?'Guardar cambios':'Crear ruta'}}</button></div></div></section>
</form>
<script id="route-clients-data" type="application/json">{!! json_encode($routeClientData, JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT) !!}</script>
<script>
if (!document.getElementById('route-clients-data')) {
const checks=[...document.querySelectorAll('.client-check')],rows=[...document.querySelectorAll('.client-row')],count=document.getElementById('selected-count');
const updateCount=()=>{const total=checks.filter(check=>check.checked).length;count.textContent=`${total} ${total===1?'seleccionado':'seleccionados'}`};
checks.forEach(check=>check.addEventListener('change',updateCount));
document.getElementById('client-search').addEventListener('input',event=>{const query=event.target.value.toLowerCase().trim();rows.forEach(row=>row.classList.toggle('hidden',!row.dataset.client.includes(query)))});
document.getElementById('select-mapped').addEventListener('click',()=>{rows.filter(row=>row.dataset.mapped==='1').forEach(row=>{const check=row.querySelector('.client-check');if(!check.disabled)check.checked=true});updateCount()});updateCount();
}
</script>
@unless($editing)<script>document.getElementById('scheduled-date')?.addEventListener('change',event=>{const end=document.getElementById('scheduled-until');end.min=event.target.value;if(end.value&&end.value<event.target.value)end.value=event.target.value});</script>@endunless
@endsection
