@extends('clients.layout')
@section('title','Rutas de cobranza')
@section('content')
@php
    $allStops=$routes->flatMap->stops; $visited=$allStops->where('status','visited')->count(); $progress=$allStops->count()?round($visited/$allStops->count()*100):0;
    $selectedStops=$selectedRoute?->stops??collect(); $mapped=$selectedStops->filter(fn($stop)=>$stop->client->latitude&&$stop->client->longitude);
    $mapPoints=$mapped->map(fn($stop)=>['lat'=>(float)$stop->client->latitude,'lng'=>(float)$stop->client->longitude,'name'=>$stop->client->full_name,'address'=>$stop->client->address,'position'=>$stop->position,'status'=>$stop->status])->values();
    $routeLabels=['planned'=>'Programada','active'=>'En recorrido','completed'=>'Finalizada','cancelled'=>'Cancelada'];
    $routeColors=['planned'=>'bg-amber-50 text-amber-700','active'=>'bg-indigo-50 text-indigo-700','completed'=>'bg-emerald-50 text-emerald-700','cancelled'=>'bg-slate-100 text-slate-500'];
    $stopLabels=['pending'=>'Pendiente','visited'=>'Visitado','not_found'=>'No encontrado','rescheduled'=>'Reprogramado'];
@endphp
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p class="text-[11px] font-semibold uppercase tracking-[.18em] text-indigo-500">Operación en campo</p><h1 class="mt-2 text-[28px] font-semibold tracking-tight">Rutas de cobranza</h1><p class="mt-1 text-sm text-slate-500">Organiza el día, ubica a tus clientes y registra cada visita.</p></div><div class="flex flex-wrap items-center gap-2"><a href="{{route('routes.index',['date'=>$date->copy()->subDay()->format('Y-m-d')])}}" class="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500">‹</a><form><input type="date" name="date" value="{{$date->format('Y-m-d')}}" onchange="this.form.submit()" class="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs font-medium"></form><a href="{{route('routes.index',['date'=>today()->format('Y-m-d')])}}" class="grid h-10 place-items-center rounded-xl bg-[#eeebff] px-4 text-xs font-semibold text-indigo-600">Hoy</a><a href="{{route('routes.index',['date'=>$date->copy()->addDay()->format('Y-m-d')])}}" class="grid h-10 w-10 place-items-center rounded-xl border border-slate-200 bg-white text-slate-500">›</a><a href="{{route('routes.create')}}" class="flex h-10 items-center gap-2 rounded-xl bg-indigo-500 px-4 text-xs font-semibold text-white shadow-lg shadow-indigo-500/20"><i data-lucide="plus" class="icon"></i>Nueva ruta</a></div></div>
<section class="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article class="card flex items-center gap-4 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-[#eeebff] text-indigo-600"><i data-lucide="route" class="icon"></i></span><div><p class="text-[11px] text-slate-400">Rutas del día</p><p class="text-xl font-semibold">{{$routes->count()}}</p></div></article><article class="card flex items-center gap-4 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600"><i data-lucide="map-pin-check" class="icon"></i></span><div><p class="text-[11px] text-slate-400">Visitas realizadas</p><p class="text-xl font-semibold">{{$visited}} <span class="text-xs font-normal text-slate-400">de {{$allStops->count()}}</span></p></div></article><article class="card flex items-center gap-4 p-4"><div class="grid h-10 w-10 place-items-center rounded-full text-xs font-semibold text-indigo-600" style="background:conic-gradient(#6366f1 {{$progress}}%,#eeebff 0)"><span class="grid h-8 w-8 place-items-center rounded-full bg-white">{{$progress}}%</span></div><div><p class="text-[11px] text-slate-400">Avance general</p><p class="text-sm font-semibold">{{$progress>=100?'Jornada completa':'En progreso'}}</p></div></article><article class="card flex items-center gap-4 p-4"><span class="grid h-10 w-10 place-items-center rounded-xl bg-amber-50 text-amber-600"><i data-lucide="map-pin" class="icon"></i></span><div><p class="text-[11px] text-slate-400">Pendientes</p><p class="text-xl font-semibold">{{$allStops->where('status','pending')->count()}}</p></div></article></section>
<section class="grid gap-5 xl:grid-cols-[330px_1fr]"><aside class="card overflow-hidden"><div class="border-b border-slate-100 p-5"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold">Rutas del día</h2><p class="mt-1 text-[11px] text-slate-400">{{$date->translatedFormat('l, d \d\e F')}}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500">{{$routes->count()}}</span></div></div><div class="max-h-[530px] space-y-2 overflow-y-auto p-3">@forelse($routes as $route)@php $done=$route->stops->where('status','visited')->count(); $routeProgress=$route->stops->count()?round($done/$route->stops->count()*100):0; @endphp<a href="{{route('routes.index',['date'=>$date->format('Y-m-d'),'route'=>$route->id])}}" class="block rounded-2xl border p-4 transition {{$selectedRoute?->id===$route->id?'border-indigo-300 bg-[#f7f5ff] shadow-sm':'border-transparent hover:border-slate-200 hover:bg-slate-50'}}"><div class="flex items-start justify-between gap-2"><span class="grid h-9 w-9 place-items-center rounded-xl {{$selectedRoute?->id===$route->id?'bg-indigo-500 text-white':'bg-[#eeebff] text-indigo-600'}}"><i data-lucide="route" class="icon"></i></span><span class="rounded-full px-2 py-1 text-[9px] font-semibold {{$routeColors[$route->status]}}">{{$routeLabels[$route->status]}}</span></div><h3 class="mt-3 text-sm font-semibold">{{$route->name}}</h3><p class="mt-1 text-[11px] text-slate-400">{{$route->starts_at?substr($route->starts_at,0,5):'Sin hora'}} · {{$route->collector->user->name}}</p><div class="mt-4 flex items-center gap-3"><div class="h-1.5 flex-1 overflow-hidden rounded-full bg-indigo-100"><div class="h-full rounded-full bg-indigo-500" style="width:{{$routeProgress}}%"></div></div><span class="text-[10px] font-semibold text-indigo-600">{{$done}}/{{$route->stops->count()}}</span></div></a>@empty<div class="px-5 py-16 text-center"><span class="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-[#eeebff] text-indigo-500"><i data-lucide="calendar-days" class="icon"></i></span><p class="mt-4 text-sm font-semibold">Día sin rutas</p><p class="mt-1 text-xs text-slate-400">Crea una ruta para comenzar.</p></div>@endforelse</div></aside>
<div class="min-w-0 space-y-5">@if($selectedRoute)<article class="card overflow-hidden"><div class="flex flex-col gap-4 border-b border-slate-100 p-5 sm:flex-row sm:items-center sm:justify-between"><div><div class="flex flex-wrap items-center gap-2"><h2 class="text-base font-semibold">{{$selectedRoute->name}}</h2><span class="rounded-full px-2.5 py-1 text-[10px] font-semibold {{$routeColors[$selectedRoute->status]}}">{{$routeLabels[$selectedRoute->status]}}</span></div><p class="mt-1 text-xs text-slate-400">{{$selectedRoute->code}} · {{$selectedRoute->collector->user->name}} · {{$selectedRoute->stops->count()}} clientes</p></div><div class="flex flex-wrap gap-2"><a href="{{route('routes.edit',$selectedRoute)}}" class="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-xs font-semibold text-slate-600"><i data-lucide="pencil" class="icon"></i>Editar</a><form method="POST" action="{{route('routes.status',$selectedRoute)}}" class="flex flex-wrap gap-2">@csrf @method('PATCH')<select name="status" aria-label="Estado de la ruta" class="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs font-semibold text-slate-600">@foreach($routeLabels as $value=>$label)<option value="{{$value}}" @selected($selectedRoute->status===$value)>{{$label}}</option>@endforeach</select><button class="rounded-xl bg-indigo-500 px-4 py-2.5 text-xs font-semibold text-white">Cambiar estado</button></form></div></div>
@if($googleMapsKey)<div id="coverage-map" class="h-[390px]"></div>@else<div class="relative grid h-[390px] place-items-center overflow-hidden bg-[#f6f3ff] p-8 text-center" style="background-image:radial-gradient(#c7c2f5 1px,transparent 1px);background-size:22px 22px"><div class="rounded-2xl border border-white/80 bg-white/90 p-6 shadow-sm backdrop-blur"><span class="mx-auto grid h-11 w-11 place-items-center rounded-xl bg-[#eeebff] text-indigo-500"><i data-lucide="map" class="icon"></i></span><h3 class="mt-3 text-sm font-semibold">Activa Google Maps</h3><p class="mt-1 max-w-xs text-xs leading-5 text-slate-500">Configura <code>GOOGLE_MAPS_API_KEY</code> y habilita Maps JavaScript API y Routes API para visualizar el recorrido.</p></div></div>@endif<div class="flex flex-wrap items-center gap-4 border-t border-slate-100 px-5 py-3 text-[10px] text-slate-500"><span class="flex items-center gap-2"><i class="h-2 w-2 rounded-full bg-indigo-500"></i>Pendiente</span><span class="flex items-center gap-2"><i class="h-2 w-2 rounded-full bg-emerald-500"></i>Visitado</span><span class="flex items-center gap-2"><i class="h-2 w-2 rounded-full bg-rose-400"></i>No encontrado</span><span id="route-distance" class="font-semibold text-slate-600"></span><span id="route-duration" class="font-semibold text-slate-600"></span><span class="ml-auto">{{$mapped->count()}} de {{$selectedStops->count()}} con coordenadas</span></div></article>
<article class="card overflow-hidden"><div class="flex items-center justify-between border-b border-slate-100 p-5"><div><h2 class="text-sm font-semibold">Clientes de esta ruta</h2><p class="mt-1 text-[11px] text-slate-400">Solo se muestran los clientes asignados. Su estado se gestiona fuera de este módulo.</p></div><span class="text-xs font-semibold text-indigo-600">{{$selectedStops->count()}} clientes</span></div><div class="divide-y divide-slate-100">@forelse($selectedStops as $stop)<div class="flex items-center gap-3 p-4"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-[#eeebff] text-xs font-semibold text-indigo-600">{{$stop->position}}</span><div class="min-w-0 flex-1"><p class="truncate text-sm font-semibold">{{$stop->client->full_name}}</p><p class="mt-1 truncate text-[11px] text-slate-400">{{$stop->client->neighborhood}} · {{$stop->client->address}}</p></div><span class="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500">Solo lectura</span></div>@empty<div class="p-8 text-center text-sm text-slate-400">Esta ruta no tiene clientes asignados.</div>@endforelse</div></article>@else<div class="card grid min-h-[540px] place-items-center p-10 text-center"><div><span class="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-[#eeebff] text-indigo-500"><i data-lucide="route" class="icon"></i></span><h2 class="mt-4 text-base font-semibold">No hay rutas programadas</h2><p class="mt-2 text-sm text-slate-400">Selecciona otra fecha o crea la primera ruta del día.</p></div></div>@endif</div></section>
@if($googleMapsKey&&$selectedRoute)<script>
(g=>{var h,a,k,p='The Google Maps JavaScript API',c='google',l='importLibrary',q='__ib__',m=document,b=window;b=b[c]||(b[c]={});var d=b.maps||(b.maps={}),r=new Set,e=new URLSearchParams,u=()=>h||(h=new Promise(async(f,n)=>{await(a=m.createElement('script'));e.set('libraries',[...r]+'');for(k in g)e.set(k.replace(/[A-Z]/g,t=>'_'+t[0].toLowerCase()),g[k]);e.set('callback',c+'.maps.'+q);a.src=`https://maps.${c}apis.com/maps/api/js?`+e;d[q]=f;a.onerror=()=>h=n(Error(p+' could not load.'));m.head.append(a)}));d[l]?console.warn(p+' only loads once. Ignoring:',g):d[l]=(f,...n)=>r.add(f)&&u().then(()=>d[l](f,...n))})({key:@json($googleMapsKey),v:'weekly'});
async function initCoverageMap(){
    const [{Map},{AdvancedMarkerElement},{Route}]=await Promise.all([google.maps.importLibrary('maps'),google.maps.importLibrary('marker'),google.maps.importLibrary('routes')]);
    const points=@json($mapPoints),center=points[0]||{lat:13.0918,lng:-86.3538};
    const map=new Map(document.getElementById('coverage-map'),{center,zoom:13,mapId:@json(config('services.google_maps.map_id')),disableDefaultUI:true,zoomControl:true});
    const bounds=new google.maps.LatLngBounds(),info=new google.maps.InfoWindow();
    points.forEach(point=>{const position={lat:point.lat,lng:point.lng},pin=document.createElement('button');pin.type='button';pin.className=`grid h-9 w-9 place-items-center rounded-full border-2 border-white text-xs font-bold text-white shadow-lg ${point.status==='visited'?'bg-emerald-500':point.status==='not_found'?'bg-rose-400':'bg-indigo-500'}`;pin.textContent=point.position;pin.setAttribute('aria-label',`${point.position}. ${point.name}`);const marker=new AdvancedMarkerElement({map,position,content:pin,title:point.name});marker.addListener('click',()=>{const content=document.createElement('div'),name=document.createElement('strong'),address=document.createElement('small');content.style.padding='4px';name.textContent=point.name;address.textContent=point.address||'Sin dirección';content.append(name,document.createElement('br'),address);info.setContent(content);info.open({map,anchor:marker})});bounds.extend(position)});
    if(points.length>1){
        let distance=0,duration=0;
        try{
            for(let start=0;start<points.length-1;start+=24){const segment=points.slice(start,Math.min(points.length,start+25)),locations=segment.map(({lat,lng})=>({lat,lng})),response=await Route.computeRoutes({origin:locations[0],destination:locations.at(-1),intermediates:locations.slice(1,-1),travelMode:'DRIVING',optimizeWaypointOrder:false,fields:['path','distanceMeters','durationMillis']});const route=response.routes?.[0];if(!route)throw new Error('Google no devolvió un recorrido');route.createPolylines().forEach(polyline=>{polyline.setOptions({strokeColor:'#4f46e5',strokeOpacity:.85,strokeWeight:5});polyline.setMap(map)});distance+=route.distanceMeters||0;duration+=route.durationMillis||0}
            document.getElementById('route-distance').textContent=`${(distance/1000).toLocaleString('es-NI',{maximumFractionDigits:1})} km`;
            document.getElementById('route-duration').textContent=`${Math.max(1,Math.round(duration/60000))} min aprox.`;
        }catch(error){console.error(error);new google.maps.Polyline({map,path:points.map(({lat,lng})=>({lat,lng})),strokeColor:'#f59e0b',strokeOpacity:.75,strokeWeight:4,icons:[{icon:{path:'M 0,-1 0,1',strokeOpacity:1,scale:3},offset:'0',repeat:'14px'}]});document.getElementById('route-distance').textContent='Ruta vial no disponible';}
        map.fitBounds(bounds,48);
    }else if(points.length===1)map.setCenter(center);
}
initCoverageMap().catch(()=>document.getElementById('coverage-map').innerHTML='<div class="grid h-full place-items-center bg-rose-50 p-6 text-center text-sm text-rose-600">No se pudo cargar Google Maps. Revisa la clave, Maps JavaScript API y Routes API.</div>');
</script>@endif
@endsection
