@extends('clients.layout')
@section('title',$collaborator->exists?'Editar colaborador':'Nuevo colaborador')
@section('content')
<div class="mb-4"><a href="{{route('collaborators.index')}}" class="flex items-center gap-2 text-xs font-semibold text-indigo-600"><i data-lucide="arrow-left" class="icon"></i>Colaboradores</a><h1 class="page-title mt-2">{{$collaborator->exists?'Editar colaborador':'Nuevo colaborador'}}</h1><p class="page-description">Configura identidad, ubicación y funciones permitidas en ruta.</p></div>
@if($errors->any())<div class="mb-4 rounded-lg border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{$collaborator->exists?route('collaborators.update',$collaborator):route('collaborators.store')}}" class="space-y-4">@csrf @if($collaborator->exists)@method('PUT')@endif
<section class="card p-4"><div class="section-heading -mx-4 -mt-4 mb-4"><h2 class="font-semibold">Cuenta e identificación</h2><p class="text-[11px] text-slate-400">Información personal y acceso al sistema</p></div><div class="grid gap-4 md:grid-cols-2 lg:grid-cols-3"><label class="field-label lg:col-span-2">Nombre completo *<input name="name" value="{{old('name',$collaborator->user?->name)}}" class="control" required></label><label class="field-label">Código interno *<input name="code" value="{{old('code',$collaborator->code)}}" class="control" placeholder="COL-001" required></label><label class="field-label">Correo *<input type="email" name="email" value="{{old('email',$collaborator->user?->email)}}" class="control" required></label><label class="field-label">Cédula<input name="identity_number" value="{{old('identity_number',$collaborator->identity_number)}}" class="control"></label><label class="field-label">Teléfono<input name="phone" value="{{old('phone',$collaborator->phone)}}" class="control"></label><label class="field-label">Contraseña {{$collaborator->exists?'':'*'}}<input type="password" name="password" class="control" {{$collaborator->exists?'':'required'}}></label><label class="field-label">Confirmar contraseña<input type="password" name="password_confirmation" class="control" {{$collaborator->exists?'':'required'}}></label><label class="field-label">Fecha de ingreso<input type="date" name="hired_at" value="{{old('hired_at',$collaborator->hired_at?->format('Y-m-d'))}}" class="control"></label></div></section>
<section class="card p-4"><div class="section-heading -mx-4 -mt-4 mb-4"><h2 class="font-semibold">Asignación territorial</h2><p class="text-[11px] text-slate-400">Sucursal, zona operativa y estado laboral</p></div><div class="grid gap-4 md:grid-cols-3"><label class="field-label">Sucursal *<select id="branch" name="branch_id" class="control" required><option value="">Seleccionar</option>@foreach($branches as $branch)<option value="{{$branch->id}}" @selected(old('branch_id',$collaborator->branch_id)==$branch->id)>{{$branch->name}}</option>@endforeach</select></label><label class="field-label">Zona<select id="zone" name="zone_id" class="control"><option value="">Todas las zonas</option>@foreach($zones as $zone)<option value="{{$zone->id}}" data-branch="{{$zone->branch_id}}" @selected(old('zone_id',$collaborator->zone_id)==$zone->id)>{{$zone->name}}</option>@endforeach</select></label><label class="field-label">Estado *<select name="status" class="control">@foreach(['active'=>'Activo','inactive'=>'Inactivo','suspended'=>'Suspendido'] as $value=>$label)<option value="{{$value}}" @selected(old('status',$collaborator->status?:'active')===$value)>{{$label}}</option>@endforeach</select></label></div></section>
<section class="card p-4"><div class="section-heading -mx-4 -mt-4 mb-4"><h2 class="font-semibold">Funciones autorizadas</h2><p class="text-[11px] text-slate-400">Selecciona una o varias responsabilidades operativas</p></div><div class="grid gap-3 md:grid-cols-3">@foreach(\App\Models\SellerProfile::CAPABILITIES as $value=>$label)<label class="flex cursor-pointer items-start gap-3 rounded-xl border border-slate-200 p-4 hover:bg-indigo-50/40"><input type="checkbox" name="capabilities[]" value="{{$value}}" @checked(in_array($value,old('capabilities',$collaborator->capabilities??[]))) class="mt-0.5 rounded border-slate-300 text-indigo-600"><span><span class="block text-sm font-semibold">{{$label}}</span><span class="mt-1 block text-[11px] text-slate-400">{{['prospecting'=>'Registrar y administrar nuevos prospectos o clientes.','credit_origination'=>'Preparar solicitudes para evaluación y aprobación.','collections'=>'Ser asignado como cobrador en rutas.'][$value]}}</span></span></label>@endforeach</div><label class="field-label mt-4 block">Observaciones<textarea name="notes" class="control" rows="3">{{old('notes',$collaborator->notes)}}</textarea></label></section>
<div class="sticky bottom-3 flex justify-end gap-2 rounded-xl border border-slate-200 bg-white/95 p-3 shadow-lg backdrop-blur"><a href="{{route('collaborators.index')}}" class="btn-secondary">Cancelar</a><button class="btn-primary"><i data-lucide="save" class="icon"></i>{{$collaborator->exists?'Guardar cambios':'Registrar colaborador'}}</button></div></form>
<script>const branch=document.getElementById('branch'),zone=document.getElementById('zone');const syncZones=()=>{[...zone.options].forEach(option=>{if(!option.value)return;option.hidden=option.dataset.branch!==branch.value});if(zone.selectedOptions[0]?.hidden)zone.value=''};branch.addEventListener('change',syncZones);syncZones();</script>
@endsection
