<script setup>
import { useForm } from '@inertiajs/vue3';
import { computed, watch } from 'vue';
import AppLayout from '../../Layouts/AppLayout.vue';
const props=defineProps({application:Object,clients:Array,sellers:Array,products:Array,guarantors:Array,editing:Boolean,endpoints:Object});
const blankGuarantee=()=>({guarantor_id:'',full_name:'',identity_number:'',phone:'',email:'',address:'',guaranteed_amount:'',guarantee_type:'personal',relationship:'',occupation:'',workplace:'',workplace_address:'',monthly_income:0,other_income:0,monthly_expenses:0,assets:'',has_overdue_obligations:false,evaluation_notes:'',accepted_at:'',identity_document:null,signed_document:null});
const existing=(props.application.guarantees||[]).map(row=>({guarantor_id:row.guarantor_id,guaranteed_amount:row.guaranteed_amount,guarantee_type:row.guarantee_type||'personal',relationship:row.relationship,monthly_income:row.latest_evaluation?.monthly_income||0,monthly_expenses:row.latest_evaluation?.monthly_expenses||0,evaluation_notes:row.latest_evaluation?.notes||''}));
const form=useForm({client_id:props.application.client_id||'',seller_id:props.application.seller_id||'',credit_product_id:props.application.credit_product_id||'',requested_amount:props.application.requested_amount||'',approved_amount:props.application.approved_amount||'',currency:props.application.currency||'NIO',purpose:props.application.purpose||'',applied_on:String(props.application.applied_on||new Date().toISOString().slice(0,10)).slice(0,10),installment_amount:props.application.installment_amount||'',term:props.application.term||1,term_value:props.application.term_value||1,term_unit:props.application.term_unit||'monthly',payment_frequency:props.application.payment_frequency||'monthly',interest_rate:props.application.interest_rate??'',interest_method:props.application.interest_method||'flat',proposed_first_payment_date:String(props.application.proposed_first_payment_date||'').slice(0,10),administrative_fee:props.application.administrative_fee||0,seller_notes:props.application.seller_notes||'',analyst_notes:props.application.analyst_notes||'',status:props.application.status||'draft',requires_guarantor:Boolean(props.application.requires_guarantor),guarantors:existing});
const selectedProduct=computed(()=>props.products.find(p=>String(p.id)===String(form.credit_product_id)));
watch(selectedProduct,p=>{if(!p)return;form.currency=p.currency||form.currency;if(p.default_interest_rate!==null&&p.default_interest_rate!==undefined)form.interest_rate=p.default_interest_rate;form.interest_method='flat';form.administrative_fee=p.default_administrative_fee||0;},{immediate:true});
const paymentRatios={daily:{daily:[1,1],weekly:[1,7],biweekly:[1,14],monthly:[1,30]},weekly:{daily:[7,1],weekly:[1,1],biweekly:[1,2],monthly:[1,4]},monthly:{daily:[30,1],weekly:[4,1],biweekly:[2,1],monthly:[1,1]},yearly:{daily:[360,1],weekly:[48,1],biweekly:[24,1],monthly:[12,1]}};
const roundMoney=value=>Math.round((value+Number.EPSILON)*100)/100;
const projection=computed(()=>{const principal=Number(form.requested_amount),rate=Number(form.interest_rate),termValue=Number(form.term_value),ratio=paymentRatios[form.term_unit]?.[form.payment_frequency];if(form.interest_rate===''||!Number.isFinite(principal)||!Number.isFinite(rate)||!Number.isInteger(termValue)||principal<=0||rate<0||termValue<1||!ratio)return{payments:0,totalRate:0,totalInterest:0,totalPayable:0,installmentAmount:0,lastPayment:0,error:''};const payments=Math.ceil((termValue*ratio[0])/ratio[1]);if(payments>365)return{payments,totalRate:0,totalInterest:0,totalPayable:0,installmentAmount:0,lastPayment:0,error:'El plazo no puede superar 365 pagos.'};const totalRate=rate*termValue,totalInterest=roundMoney(principal*(totalRate/100)),totalPayable=roundMoney(principal+totalInterest),installmentAmount=roundMoney(totalPayable/payments),lastPayment=roundMoney(totalPayable-(installmentAmount*(payments-1)));return{payments,totalRate,totalInterest,totalPayable,installmentAmount,lastPayment,error:''};});
const payments=computed(()=>projection.value.payments);
const money=value=>new Intl.NumberFormat('es-NI',{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value||0));
watch(projection,value=>{form.term=value.error?'':(value.payments||'');form.installment_amount=value.error?'':(value.installmentAmount>0?value.installmentAmount.toFixed(2):'');},{immediate:true});
const addGuarantee=()=>form.guarantors.push(blankGuarantee());
const submit=()=>form.transform(data=>props.editing?{...data,_method:'put'}:data).post(props.endpoints.save,{forceFormData:true});
</script>
<template><AppLayout :title="editing?'Editar solicitud':'Nueva solicitud'" eyebrow="Originación" description="Conserva las condiciones aprobadas por producto y registra la evaluación sin alterar reglas financieras."><template #header-actions><a :href="endpoints.index" class="btn-secondary">Volver</a></template><form class="space-y-4" @submit.prevent="submit"><div v-if="Object.keys(form.errors).length" class="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700"><p v-for="(error,key) in form.errors" :key="key">{{error}}</p></div>
<section class="card p-5"><h2 class="font-semibold">Cliente y producto</h2><div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><label class="field-label md:col-span-2">Cliente *<select v-model="form.client_id" class="control" required><option value="">Seleccionar</option><option v-for="client in clients" :key="client.id" :value="client.id" :disabled="client.open_loans_count>0&&client.id!==application.client_id">{{client.full_name}} · {{client.code}}{{client.open_loans_count?' · crédito vigente':''}}</option></select></label><label class="field-label">Gestor *<select v-model="form.seller_id" class="control" required><option value="">Seleccionar</option><option v-for="seller in sellers" :key="seller.id" :value="seller.id">{{seller.display_name}} · {{seller.code}}</option></select></label><label class="field-label">Producto *<select v-model="form.credit_product_id" class="control" required><option value="">Seleccionar</option><option v-for="product in products" :key="product.id" :value="product.id">{{product.name}}</option></select></label></div></section>
<section class="card p-5">
    <h2 class="font-semibold">Condiciones solicitadas</h2>
    <div class="mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        <label class="field-label">Monto solicitado *<input v-model="form.requested_amount" type="number" step=".01" min=".01" class="control" required></label>
        <label class="field-label">Moneda<select v-model="form.currency" class="control"><option>NIO</option><option>USD</option></select></label>
        <label class="field-label">Tasa por período (%) *<input v-model="form.interest_rate" type="number" min="0" step=".000001" class="control" required><span class="mt-1 block text-[10px] font-normal text-slate-400">Se multiplica por la cantidad indicada en el plazo.</span></label>
        <label class="field-label">Plazo *<input v-model.number="form.term_value" type="number" min="1" max="365" step="1" class="control" required></label>
        <label class="field-label">Unidad del plazo *<select v-model="form.term_unit" class="control" required><option value="daily">Días</option><option value="weekly">Semanas</option><option value="monthly">Meses</option><option value="yearly">Años</option></select></label>
        <label class="field-label">Frecuencia de pago *<select v-model="form.payment_frequency" class="control" required><option value="daily">Diaria</option><option value="weekly">Semanal</option><option value="biweekly">Quincenal</option><option value="monthly">Mensual</option></select></label>
        <label class="field-label">Pagos calculados<input v-model="form.term" type="number" min="1" max="365" class="control bg-slate-50" readonly></label>
        <label class="field-label">Pago calculado<input v-model="form.installment_amount" type="number" step=".01" min=".01" class="control bg-slate-50" readonly></label>
        <label class="field-label">Fecha de solicitud<input v-model="form.applied_on" type="date" class="control"></label>
        <label class="field-label xl:col-span-4">Destino del crédito *<textarea v-model="form.purpose" class="control" required></textarea></label>
    </div>
    <div v-if="projection.error" class="mt-4 rounded-lg bg-rose-50 p-3 text-xs font-semibold text-rose-700">{{ projection.error }}</div>
    <div v-else class="mt-4 grid gap-3 rounded-xl bg-blue-50 p-4 text-xs text-blue-800 sm:grid-cols-2 xl:grid-cols-5">
        <div><span class="block text-[10px] uppercase tracking-wide text-blue-500">Tasa total</span><strong>{{ Number(projection.totalRate).toLocaleString('es-NI', { maximumFractionDigits: 6 }) }}%</strong></div>
        <div><span class="block text-[10px] uppercase tracking-wide text-blue-500">Interés total</span><strong>{{ form.currency }} {{ money(projection.totalInterest) }}</strong></div>
        <div><span class="block text-[10px] uppercase tracking-wide text-blue-500">Monto total</span><strong>{{ form.currency }} {{ money(projection.totalPayable) }}</strong></div>
        <div><span class="block text-[10px] uppercase tracking-wide text-blue-500">Cantidad de pagos</span><strong>{{ payments || 0 }}</strong></div>
        <div><span class="block text-[10px] uppercase tracking-wide text-blue-500">Pago regular</span><strong>{{ form.currency }} {{ money(projection.installmentAmount) }}</strong><span v-if="projection.payments>1&&projection.lastPayment!==projection.installmentAmount" class="mt-1 block text-[10px]">Último: {{ form.currency }} {{ money(projection.lastPayment) }}</span></div>
    </div>
    <p class="mt-3 text-[11px] text-slate-500">Conversión comercial: 1 mes = 4 semanas = 2 quincenas = 30 días; 1 año = 12 meses. El servidor recalcula y valida estos valores al guardar.</p>
</section>
<section class="card overflow-hidden"><div class="section-heading flex items-center justify-between"><div><h2 class="font-semibold">Fiadores</h2><p class="text-[11px] text-slate-400">Evaluación independiente por solicitud.</p></div><label class="flex items-center gap-2 text-xs"><input v-model="form.requires_guarantor" type="checkbox"> Requiere fiador</label></div><div v-for="(row,index) in form.guarantors" :key="index" class="grid gap-4 border-b p-5 md:grid-cols-2 xl:grid-cols-4"><label class="field-label xl:col-span-2">Fiador registrado<select v-model="row.guarantor_id" class="control"><option value="">Registrar nuevo</option><option v-for="person in guarantors" :key="person.id" :value="person.id">{{person.full_name}} · {{person.identity_number}}</option></select></label><label class="field-label">Nombre nuevo<input v-model="row.full_name" class="control"></label><label class="field-label">Cédula<input v-model="row.identity_number" class="control"></label><label class="field-label">Relación *<input v-model="row.relationship" class="control"></label><label class="field-label">Monto garantizado *<input v-model="row.guaranteed_amount" type="number" step=".01" class="control"></label><label class="field-label">Ingresos *<input v-model="row.monthly_income" type="number" step=".01" class="control"></label><label class="field-label">Gastos *<input v-model="row.monthly_expenses" type="number" step=".01" class="control"></label><label class="field-label">Documento de identidad<input type="file" class="control" @change="row.identity_document=$event.target.files[0]"></label><label class="field-label">Garantía firmada<input type="file" class="control" @change="row.signed_document=$event.target.files[0]"></label><label class="flex items-center gap-2 text-xs text-rose-600"><input v-model="row.has_overdue_obligations" type="checkbox"> Obligaciones vencidas</label><button type="button" class="text-left text-xs font-semibold text-rose-600" @click="form.guarantors.splice(index,1)">Quitar fiador</button></div><div class="p-4"><button type="button" class="btn-soft" @click="addGuarantee">Agregar fiador</button></div></section>
<section class="card p-5"><div class="grid gap-4 md:grid-cols-2"><label class="field-label">Notas del vendedor<textarea v-model="form.seller_notes" class="control"></textarea></label><label class="field-label">Notas del analista<textarea v-model="form.analyst_notes" class="control"></textarea></label><label class="field-label">Estado<select v-model="form.status" class="control"><option value="draft">Borrador</option><option value="submitted">Enviada</option><option value="review">En revisión</option></select></label></div></section><div class="flex justify-end gap-2"><a :href="endpoints.index" class="btn-secondary">Cancelar</a><button class="btn-primary" :disabled="form.processing||Boolean(projection.error)">{{form.processing?'Guardando…':'Guardar solicitud'}}</button></div></form></AppLayout></template>
