@extends('clients.layout')
@section('title',$product->exists?'Editar producto':'Nuevo producto')
@section('content')
@php
    $input='mt-1.5 w-full rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100';
    $label='text-xs font-medium text-slate-600';
    $frequencies=['daily'=>'Diaria','weekly'=>'Semanal','biweekly'=>'Quincenal','monthly'=>'Mensual'];
    $interestMethods=['flat'=>'Interés plano','declining_balance'=>'Saldo decreciente','french'=>'Cuota nivelada'];
    $components=['delinquency'=>'Mora','fees'=>'Cargos','interest'=>'Interés','principal'=>'Capital'];
    $selectedFrequencies=old('allowed_frequencies',$product->allowed_frequencies??[]);
    $selectedMethods=old('allowed_interest_methods',$product->allowed_interest_methods??[]);
    $selectedOrder=old('payment_allocation_order',$product->payment_allocation_order??array_keys($components));
@endphp
<div class="mb-6"><a href="{{route('products.index')}}" class="text-xs font-semibold text-indigo-500">← Volver</a><h1 class="mt-4 text-[28px] font-semibold">{{$product->exists?'Editar producto':'Nuevo producto financiero'}}</h1><p class="mt-1 text-sm text-slate-500">Configura las reglas aplicables a operaciones nuevas.</p></div>
@if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
<form method="POST" action="{{$product->exists?route('products.update',$product):route('products.store')}}" class="space-y-5">
    @csrf
    @if($product->exists) @method('PUT') @endif
    <section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Información general</h2><div class="grid gap-5 md:grid-cols-3"><label class="{{$label}}">Código *<input name="code" value="{{old('code',$product->code)}}" class="{{$input}}" required></label><label class="{{$label}} md:col-span-2">Nombre *<input name="name" value="{{old('name',$product->name)}}" class="{{$input}}" required></label><label class="{{$label}}">Moneda<select name="currency" class="{{$input}}"><option value="NIO">Córdobas</option><option value="USD" @selected(old('currency',$product->currency)==='USD')>Dólares</option></select></label><label class="flex items-center gap-2 pt-7 text-xs font-medium text-slate-600"><input type="checkbox" name="is_active" value="1" @checked(old('is_active',$product->exists?$product->is_active:true)) class="rounded text-indigo-500">Producto activo</label></div></section>
    <section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Interés, plazo y frecuencia</h2><div class="grid gap-5 md:grid-cols-3"><label class="{{$label}}">Tasa predeterminada (%)<input type="number" step="0.000001" min="0" name="default_interest_rate" value="{{old('default_interest_rate',$product->default_interest_rate)}}" class="{{$input}}"></label><label class="{{$label}}">Método predeterminado<select name="default_interest_method" class="{{$input}}"><option value="">Sin definir</option>@foreach($interestMethods as $methodKey=>$methodLabel)<option value="{{$methodKey}}" @selected(old('default_interest_method',$product->default_interest_method)===$methodKey)>{{$methodLabel}}</option>@endforeach</select></label><label class="{{$label}}">Gastos administrativos<input type="number" step="0.01" min="0" name="default_administrative_fee" value="{{old('default_administrative_fee',$product->default_administrative_fee?:0)}}" class="{{$input}}" required></label><label class="{{$label}}">Plazo mínimo<input type="number" min="1" name="minimum_term" value="{{old('minimum_term',$product->minimum_term?:1)}}" class="{{$input}}" required></label><label class="{{$label}}">Plazo máximo<input type="number" min="1" name="maximum_term" value="{{old('maximum_term',$product->maximum_term?:60)}}" class="{{$input}}" required></label><div><p class="{{$label}}">Frecuencias permitidas *</p><div class="mt-3 flex flex-wrap gap-3">@foreach($frequencies as $frequencyKey=>$frequencyLabel)<label class="flex items-center gap-2 text-xs"><input type="checkbox" name="allowed_frequencies[]" value="{{$frequencyKey}}" @checked(in_array($frequencyKey,$selectedFrequencies,true)) class="rounded text-indigo-500">{{$frequencyLabel}}</label>@endforeach</div></div><div class="md:col-span-3"><p class="{{$label}}">Métodos permitidos *</p><div class="mt-3 flex flex-wrap gap-4">@foreach($interestMethods as $methodKey=>$methodLabel)<label class="flex items-center gap-2 text-xs"><input type="checkbox" name="allowed_interest_methods[]" value="{{$methodKey}}" @checked(in_array($methodKey,$selectedMethods,true)) class="rounded text-indigo-500">{{$methodLabel}}</label>@endforeach</div></div></div></section>
    <section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Mora y aplicación de pagos</h2><div class="grid gap-5 md:grid-cols-2"><label class="{{$label}}">Método de mora<select name="delinquency_method" class="{{$input}}"><option value="">Sin definir</option><option value="none" @selected(old('delinquency_method',$product->delinquency_method)==='none')>Sin mora automática</option><option value="daily_percentage" @selected(old('delinquency_method',$product->delinquency_method)==='daily_percentage')>Porcentaje diario</option><option value="fixed" @selected(old('delinquency_method',$product->delinquency_method)==='fixed')>Monto fijo</option></select></label><label class="{{$label}}">Tasa o monto de mora<input type="number" step="0.000001" min="0" name="delinquency_rate" value="{{old('delinquency_rate',$product->delinquency_rate)}}" class="{{$input}}"></label><div class="md:col-span-2"><p class="{{$label}}">Orden de aplicación *</p><div class="mt-3 grid gap-3 sm:grid-cols-4">@foreach([0,1,2,3] as $position)<label class="text-[10px] font-semibold text-slate-400">{{$position+1}}°<select name="payment_allocation_order[]" class="{{$input}}">@foreach($components as $componentKey=>$componentLabel)<option value="{{$componentKey}}" @selected(($selectedOrder[$position]??'')===$componentKey)>{{$componentLabel}}</option>@endforeach</select></label>@endforeach</div><p class="mt-3 text-[10px] text-slate-400">Cada componente debe aparecer una sola vez.</p></div></div></section>
    <div class="flex justify-end"><button class="rounded-xl bg-indigo-500 px-5 py-2.5 text-xs font-semibold text-white">Guardar configuración</button></div>
</form>
@endsection
