@extends('clients.layout')
@section('title','Apariencia')
@section('content')
<div class="mb-6"><h1 class="text-[28px] font-semibold">Identidad visual</h1><p class="mt-1 text-sm text-slate-500">Define libremente los colores y el estilo visual de todo el sistema.</p></div>@include('settings._tabs')
@if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
@php
$fonts=['instrument'=>['Instrument Sans','Moderna y limpia'],'inter'=>['Inter','Alta legibilidad'],'system'=>['Sistema','Rápida y neutral'],'humanist'=>['Humanista','Amable y profesional'],'nunito'=>['Nunito','Suave y accesible'],'poppins'=>['Poppins','Geométrica y moderna'],'roboto'=>['Roboto','Versátil y familiar'],'lato'=>['Lato','Corporativa y cálida'],'serif'=>['Serif clásica','Formal y editorial'],'merriweather'=>['Merriweather','Elegante para reportes'],'georgia'=>['Georgia','Tradicional e institucional'],'mono'=>['Monoespaciada','Técnica y numérica']];
$input='mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm';
@endphp
<form method="POST" action="{{route('settings.appearance.update')}}">@csrf @method('PUT')
<div class="grid gap-5 lg:grid-cols-2"><section class="card p-6"><h2 class="text-sm font-semibold">Colores personalizados</h2><p class="mb-5 mt-1 text-xs text-slate-500">Cada color se conserva hasta que vuelvas a modificarlo.</p><div class="grid gap-5 sm:grid-cols-2">@foreach(['primary_color'=>['Color principal','#6366f1'],'sidebar_color'=>['Menú lateral','#10172a'],'accent_color'=>['Color de acento','#22d3ee'],'background_color'=>['Fondo general','#f5f7fb']] as $key=>[$label,$fallback])<label class="text-xs font-medium text-slate-600">{{$label}}<div class="mt-2 flex gap-2"><input id="{{$key}}" type="color" name="{{$key}}" value="{{old($key,$settings[$key]??$fallback)}}" class="h-11 w-14 rounded border"><output data-for="{{$key}}" class="grid flex-1 place-items-center rounded-xl border border-slate-200 font-mono text-xs"></output></div></label>@endforeach</div></section>
<section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Tipografía y estructura</h2><label class="text-xs font-medium text-slate-600">Familia tipográfica<select id="font_family" name="font_family" class="{{$input}}">@foreach($fonts as $key=>[$name,$description])<option value="{{$key}}" @selected(old('font_family',$settings['font_family']??'inter')===$key)>{{$name}} · {{$description}}</option>@endforeach</select></label><div id="font-preview" class="mt-4 rounded-xl border border-slate-100 bg-slate-50 p-4"><p class="text-base font-semibold">Centro Financiero 360</p><p class="mt-1 text-xs text-slate-500">Crédito PRE-000128 · Saldo C$ 24,850.00</p></div><div class="mt-5 grid gap-4 sm:grid-cols-2"><label class="text-xs font-medium text-slate-600">Densidad<select name="density" class="{{$input}}"><option value="comfortable" @selected(($settings['density']??'comfortable')==='comfortable')>Cómoda</option><option value="compact" @selected(($settings['density']??'')==='compact')>Compacta</option></select></label><label class="text-xs font-medium text-slate-600">Bordes<select name="border_radius" class="{{$input}}"><option value="soft" @selected(($settings['border_radius']??'soft')==='soft')>Suaves</option><option value="rounded" @selected(($settings['border_radius']??'')==='rounded')>Muy redondeados</option><option value="square" @selected(($settings['border_radius']??'')==='square')>Rectos</option></select></label></div></section></div>
<section id="identity-preview" class="mt-5 overflow-hidden rounded-xl border bg-white"><div id="preview-sidebar" class="flex items-center gap-3 px-5 py-4 text-white"><span id="preview-logo" class="grid h-9 w-9 place-items-center rounded-lg text-xs font-bold">360</span><div><strong class="text-sm">Vista previa</strong><p class="text-[10px] opacity-70">Identidad aplicada al sistema</p></div><button id="preview-button" type="button" class="ml-auto rounded-lg px-4 py-2 text-xs font-semibold text-white">Acción principal</button></div></section>
<div class="mt-5 flex justify-end"><button class="rounded-xl bg-indigo-500 px-5 py-2.5 text-xs font-semibold text-white">Guardar identidad visual</button></div></form>
<script>const fonts={instrument:'Instrument Sans,system-ui,sans-serif',inter:'Inter,Arial,sans-serif',system:'system-ui,sans-serif',humanist:'Segoe UI,Trebuchet MS,sans-serif',nunito:'Nunito,Trebuchet MS,sans-serif',poppins:'Poppins,Century Gothic,sans-serif',roboto:'Roboto,Arial,sans-serif',lato:'Lato,Arial,sans-serif',serif:'Georgia,Cambria,serif',merriweather:'Merriweather,Georgia,serif',georgia:'Georgia,serif',mono:'Cascadia Code,Consolas,monospace'},keys=['primary_color','sidebar_color','accent_color','background_color'],byId=id=>document.getElementById(id);function preview(){keys.forEach(k=>document.querySelector(`[data-for="${k}"]`).textContent=byId(k).value);byId('preview-sidebar').style.background=byId('sidebar_color').value;byId('preview-logo').style.background=`linear-gradient(135deg,${byId('primary_color').value},${byId('accent_color').value})`;byId('preview-button').style.background=byId('primary_color').value;byId('identity-preview').style.background=byId('background_color').value;byId('font-preview').style.fontFamily=fonts[byId('font_family').value]}document.querySelectorAll('input[type=color]').forEach(input=>input.addEventListener('input',preview));byId('font_family').addEventListener('change',preview);preview();</script>
@endsection
