@extends('clients.layout')
@section('title','Marca del sistema')
@section('content')
<div class="mb-6"><h1 class="text-[28px] font-semibold">Marca del sistema</h1><p class="mt-1 text-sm text-slate-500">Personaliza el nombre y logotipo que identifican la plataforma.</p></div>@include('settings._tabs')
@if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
@php $input='mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-400'; @endphp
<form method="POST" action="{{route('settings.brand.update')}}" enctype="multipart/form-data" class="grid gap-5 lg:grid-cols-[1fr_360px]">@csrf @method('PUT')
<section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Identificación</h2><div class="space-y-5"><label class="block text-xs font-medium text-slate-600">Nombre del sistema *<input name="system_name" value="{{old('system_name',$settings['system_name']??'Centro Financiero 360')}}" maxlength="80" required class="{{$input}}"><span class="mt-1 block text-[10px] text-slate-400">Aparece en el menú y título del navegador.</span></label><label class="block text-xs font-medium text-slate-600">Descripción corta<input name="system_tagline" value="{{old('system_tagline',$settings['system_tagline']??'Operación 360°')}}" maxlength="120" class="{{$input}}"></label><label class="block text-xs font-medium text-slate-600">Nuevo logotipo<input id="logo-input" type="file" name="logo" accept=".png,.jpg,.jpeg,.webp" class="{{$input}}"><span class="mt-1 block text-[10px] text-slate-400">PNG, JPG o WebP; mínimo 64×64 px y máximo 2 MB.</span></label>@if(filled($settings['logo_path']??null))<label class="flex items-center gap-2 text-xs font-semibold text-rose-600"><input type="checkbox" name="remove_logo" value="1" class="rounded text-rose-500">Eliminar logotipo actual</label>@endif</div><div class="mt-6 flex justify-end"><button class="rounded-xl bg-indigo-500 px-5 py-2.5 text-xs font-semibold text-white">Guardar marca</button></div></section>
<aside class="card p-6"><h2 class="text-sm font-semibold">Vista previa</h2><div class="mt-5 rounded-xl bg-[#10172a] p-5 text-white"><div class="flex items-center gap-3"><div id="logo-preview-wrap" class="grid h-12 w-12 place-items-center overflow-hidden rounded-xl bg-gradient-to-br from-indigo-500 to-cyan-400 text-sm font-bold">@if(filled($settings['logo_path']??null))<img src="{{route('settings.logo',['v'=>optional(\App\Models\SystemSetting::where('key','logo_path')->first())->updated_at?->timestamp])}}" class="h-full w-full bg-white object-contain p-1" alt="Logo actual">@else<span>360</span>@endif</div><div class="min-w-0"><p id="name-preview" class="truncate text-sm font-semibold">{{$settings['system_name']??'Centro Financiero 360'}}</p><p id="tagline-preview" class="truncate text-[10px] text-slate-400">{{$settings['system_tagline']??'Operación 360°'}}</p></div></div></div></aside></form>
<script>const n=document.querySelector('[name=system_name]'),t=document.querySelector('[name=system_tagline]'),f=document.getElementById('logo-input');n.addEventListener('input',()=>document.getElementById('name-preview').textContent=n.value||'Nombre del sistema');t.addEventListener('input',()=>document.getElementById('tagline-preview').textContent=t.value||'Descripción');f.addEventListener('change',()=>{const file=f.files[0];if(!file)return;const image=document.createElement('img');image.className='h-full w-full bg-white object-contain p-1';image.src=URL.createObjectURL(file);document.getElementById('logo-preview-wrap').replaceChildren(image)});</script>
@endsection
