@extends('clients.layout')
@section('title','Configuración institucional')
@section('content')
<div class="mb-6"><h1 class="text-[28px] font-semibold">Institución y sistema</h1><p class="mt-1 text-sm text-slate-500">Información usada en encabezados, documentos y operación diaria.</p></div>@include('settings._tabs')
@if($errors->any())<div class="mb-5 rounded-xl bg-rose-50 p-4 text-sm text-rose-700"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{$error}}</li>@endforeach</ul></div>@endif
@php $input='mt-1.5 w-full rounded-xl border border-slate-200 px-3.5 py-2.5 text-sm outline-none focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100';$label='text-xs font-medium text-slate-600'; @endphp
<form method="POST" action="{{route('settings.general.update')}}" class="space-y-5">@csrf @method('PUT')
<section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Identidad institucional</h2><div class="grid gap-5 md:grid-cols-2"><label class="{{$label}}">Nombre comercial *<input name="institution_name" value="{{old('institution_name',$settings['institution_name']??'')}}" required class="{{$input}}"></label><label class="{{$label}}">Razón social<input name="legal_name" value="{{old('legal_name',$settings['legal_name']??'')}}" class="{{$input}}"></label><label class="{{$label}}">RUC / identificación fiscal<input name="tax_id" value="{{old('tax_id',$settings['tax_id']??'')}}" class="{{$input}}"></label><label class="{{$label}}">Teléfono<input name="phone" value="{{old('phone',$settings['phone']??'')}}" class="{{$input}}"></label><label class="{{$label}}">Correo<input type="email" name="email" value="{{old('email',$settings['email']??'')}}" class="{{$input}}"></label><label class="{{$label}}">Dirección<textarea name="address" rows="2" class="{{$input}}">{{old('address',$settings['address']??'')}}</textarea></label></div></section>
<section class="card p-6"><h2 class="mb-5 text-sm font-semibold">Regionalización</h2><div class="grid gap-5 md:grid-cols-3"><label class="{{$label}}">Zona horaria<select name="timezone" class="{{$input}}"><option value="America/Managua">America/Managua</option></select></label><label class="{{$label}}">Formato de fecha<select name="date_format" class="{{$input}}"><option value="d/m/Y" @selected(($settings['date_format']??'d/m/Y')==='d/m/Y')>DD/MM/AAAA</option><option value="Y-m-d" @selected(($settings['date_format']??'')==='Y-m-d')>AAAA-MM-DD</option></select></label><label class="{{$label}}">Moneda base<input value="NIO · Córdoba nicaragüense" disabled class="{{$input}} bg-slate-50 text-slate-500"><span class="mt-1 block text-[10px] text-slate-400">Protegida por la política del sistema.</span></label></div></section>
<div class="flex justify-end"><button class="rounded-xl bg-indigo-500 px-5 py-2.5 text-xs font-semibold text-white"><i data-lucide="save" class="icon mr-2 inline"></i>Guardar cambios</button></div></form>
@endsection
