<script setup>
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';

const props = defineProps({ loginUrl: String, forgotPasswordUrl: String });
const page = usePage();
const form = useForm({ email: '', password: '', remember: false });
const submit = () => form.post(props.loginUrl, { preserveScroll: true, onFinish: () => form.reset('password') });
</script>

<template>
    <Head title="Iniciar sesión" />
    <main class="login-shell" :class="`theme-${page.props.appearance?.theme === 'day' ? 'day' : 'night'}`">
        <section class="login-story"><div class="login-glow login-glow-one"></div><div class="login-glow login-glow-two"></div><header class="relative z-10 flex items-center gap-3"><img v-if="page.props.brand?.logo_url" :src="page.props.brand.logo_url" alt="Logotipo" class="h-12 w-12 rounded-2xl bg-white object-contain p-1.5"><span v-else class="grid h-12 w-12 place-items-center rounded-2xl bg-blue-500 text-lg font-black text-white">F</span><div><strong class="block text-sm text-white">{{ page.props.brand?.system_name || 'Financiera' }}</strong><span class="text-[11px] text-slate-400">{{ page.props.brand?.system_tagline || 'Gestión integral' }}</span></div></header><div class="relative z-10 max-w-xl"><p class="premium-kicker"><i></i> Acceso protegido</p><h1 class="mt-5 text-4xl font-semibold leading-[1.08] tracking-[-.04em] text-white sm:text-5xl">Crédito cercano.<br><span class="text-sky-300">Decisiones con visión.</span></h1><p class="mt-5 max-w-lg text-sm leading-6 text-slate-400">Acceso exclusivo para personal autorizado.</p></div></section>
        <section class="login-access"><div class="w-full max-w-md"><div class="mb-9"><p class="eyebrow">Acceso seguro</p><h2 class="mt-2 text-3xl font-semibold tracking-[-.035em] text-slate-950">Bienvenido de vuelta</h2><p class="mt-2 text-sm leading-6 text-slate-500">Ingresa tu correo institucional y contraseña.</p></div><form class="space-y-5" @submit.prevent="submit"><label class="field-label">Correo electrónico<input v-model="form.email" type="email" autocomplete="username" autofocus class="control login-control" placeholder="nombre@financiera.com" required></label><label class="field-label">Contraseña<input v-model="form.password" type="password" autocomplete="current-password" class="control login-control" placeholder="••••••••" required></label><div class="flex items-center justify-between gap-4"><label class="flex items-center gap-2 text-xs font-medium text-slate-600"><input v-model="form.remember" type="checkbox" class="accent-blue-600"> Mantener sesión</label><Link :href="forgotPasswordUrl" class="text-xs font-semibold text-blue-700">Recuperar acceso</Link></div><p v-if="form.errors.email || form.errors.password" class="rounded-xl border border-rose-400/20 bg-rose-500/10 p-3 text-xs font-medium text-rose-700">{{ form.errors.email || form.errors.password }}</p><button class="btn-primary h-12 w-full rounded-xl text-sm" :disabled="form.processing">{{ form.processing ? 'Verificando…' : 'Ingresar al sistema' }}</button></form></div></section>
    </main>
</template>